=== sergiowww/chessmine/chessmine/src/main/resources/board_state.dtd
<!ELEMENT board_setup (piece+, target)>

<!ELEMENT piece (type, line, col, (white|black))>
<!ELEMENT type (#PCDATA)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT col (#PCDATA)>
<!ELEMENT white EMPTY>
<!ELEMENT black EMPTY>

<!ELEMENT target (#PCDATA)>

<!ATTLIST piece id ID #REQUIRED>

=== sergiowww/chessmine/chessmine/src/main/resources/board_state.xml
<?xml version="1.0"?>
<!DOCTYPE board_setup SYSTEM "board_state.dtd">
<board_setup>
	<piece id="p1">
		<type>1</type>
		<line>7</line>
		<col>1</col>
		<white/>
	</piece>
	<piece id="p2">
		<type>1</type>
		<line>7</line>
		<col>2</col>
		<white/>
	</piece>
	<piece id="p3">
		<type>1</type>
		<line>7</line>
		<col>3</col>
		<white/>
	</piece>
	<piece id="p4">
		<type>1</type>
		<line>7</line>
		<col>4</col>
		<white/>
	</piece>
	<piece id="p5">
		<type>1</type>
		<line>7</line>
		<col>5</col>
		<white/>
	</piece>
	<piece id="p6">
		<type>1</type>
		<line>7</line>
		<col>6</col>
		<white/>
	</piece>
	<piece id="p7">
		<type>1</type>
		<line>7</line>
		<col>7</col>
		<white/>
	</piece>
	<piece id="p8">
		<type>1</type>
		<line>7</line>
		<col>8</col>
		<white/>
	</piece>
	<piece id="p9">
		<type>2</type>
		<line>8</line>
		<col>2</col>
		<white/>
	</piece>
	<piece id="p10">
		<type>2</type>
		<line>8</line>
		<col>7</col>
		<white/>
	</piece>
	<piece id="p11">
		<type>3</type>
		<line>8</line>
		<col>3</col>
		<white/>
	</piece>
	<piece id="p12">
		<type>3</type>
		<line>8</line>
		<col>6</col>
		<white/>
	</piece>
	<piece id="p13">
		<type>4</type>
		<line>8</line>
		<col>1</col>
		<white/>
	</piece>
	<piece id="p14">
		<type>4</type>
		<line>8</line>
		<col>8</col>
		<white/>
	</piece>
	<piece id="p15">
		<type>5</type>
		<line>8</line>
		<col>5</col>
		<white/>
	</piece>
	<piece id="p16">
		<type>6</type>
		<line>8</line>
		<col>4</col>
		<white/>
	</piece>
	<piece id="p17">
		<type>1</type>
		<line>2</line>
		<col>1</col>
		<black/>
	</piece>
	<piece id="p18">
		<type>1</type>
		<line>2</line>
		<col>2</col>
		<black/>
	</piece>
	<piece id="p19">
		<type>1</type>
		<line>2</line>
		<col>3</col>
		<black/>
	</piece>
	<piece id="p20">
		<type>1</type>
		<line>2</line>
		<col>4</col>
		<black/>
	</piece>
	<piece id="p21">
		<type>1</type>
		<line>2</line>
		<col>5</col>
		<black/>
	</piece>
	<piece id="p22">
		<type>1</type>
		<line>2</line>
		<col>6</col>
		<black/>
	</piece>
	<piece id="p23">
		<type>1</type>
		<line>2</line>
		<col>7</col>
		<black/>
	</piece>
	<piece id="p24">
		<type>1</type>
		<line>2</line>
		<col>8</col>
		<black/>
	</piece>
	<piece id="p25">
		<type>2</type>
		<line>1</line>
		<col>2</col>
		<black/>
	</piece>
	<piece id="p26">
		<type>2</type>
		<line>1</line>
		<col>7</col>
		<black/>
	</piece>
	<piece id="p27">
		<type>3</type>
		<line>1</line>
		<col>3</col>
		<black/>
	</piece>
	<piece id="p28">
		<type>3</type>
		<line>1</line>
		<col>6</col>
		<black/>
	</piece>
	<piece id="p29">
		<type>4</type>
		<line>1</line>
		<col>1</col>
		<black/>
	</piece>
	<piece id="p30">
		<type>4</type>
		<line>1</line>
		<col>8</col>
		<black/>
	</piece>
	<piece id="p31">
		<type>5</type>
		<line>1</line>
		<col>5</col>
		<black/>
	</piece>
	<piece id="p32">
		<type>6</type>
		<line>1</line>
		<col>4</col>
		<black/>
	</piece>
	<target>p5</target>
</board_setup>
