=== sergiowww/chessmine/chessmine/src/main/resources/board_result.dtd
<!ELEMENT board_result (square+)>

<!ELEMENT square (pieceId, line, col, (white|black|none))>
<!ELEMENT pieceId (#PCDATA)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT col (#PCDATA)>
<!ELEMENT white EMPTY>
<!ELEMENT black EMPTY>
<!ELEMENT none EMPTY>

=== sergiowww/chessmine/chessmine/src/main/resources/board_result.xml
<?xml version="1.0" ?>
<!DOCTYPE board_result SYSTEM "board_result.dtd">
<board_result>
	<square>
		<pieceId>1</pieceId>
		<line>7</line>
		<col>1</col>
		<white/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>7</line>
		<col>2</col>
		<white/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>7</line>
		<col>3</col>
		<white/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>7</line>
		<col>4</col>
		<white/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>7</line>
		<col>5</col>
		<white/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>7</line>
		<col>6</col>
		<white/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>7</line>
		<col>7</col>
		<white/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>7</line>
		<col>8</col>
		<white/>
	</square>
	<square>
		<pieceId>2</pieceId>
		<line>8</line>
		<col>2</col>
		<white/>
	</square>
	<square>
		<pieceId>2</pieceId>
		<line>8</line>
		<col>7</col>
		<white/>
	</square>
	<square>
		<pieceId>3</pieceId>
		<line>8</line>
		<col>3</col>
		<white/>
	</square>
	<square>
		<pieceId>3</pieceId>
		<line>8</line>
		<col>6</col>
		<white/>
	</square>
	<square>
		<pieceId>4</pieceId>
		<line>8</line>
		<col>1</col>
		<white/>
	</square>
	<square>
		<pieceId>4</pieceId>
		<line>8</line>
		<col>8</col>
		<white/>
	</square>
	<square>
		<pieceId>5</pieceId>
		<line>8</line>
		<col>5</col>
		<white/>
	</square>
	<square>
		<pieceId>6</pieceId>
		<line>8</line>
		<col>4</col>
		<white/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>2</line>
		<col>1</col>
		<black/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>2</line>
		<col>2</col>
		<black/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>2</line>
		<col>3</col>
		<black/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>2</line>
		<col>4</col>
		<black/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>2</line>
		<col>5</col>
		<black/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>2</line>
		<col>6</col>
		<black/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>2</line>
		<col>7</col>
		<black/>
	</square>
	<square>
		<pieceId>1</pieceId>
		<line>2</line>
		<col>8</col>
		<black/>
	</square>
	<square>
		<pieceId>2</pieceId>
		<line>1</line>
		<col>2</col>
		<black/>
	</square>
	<square>
		<pieceId>2</pieceId>
		<line>1</line>
		<col>7</col>
		<black/>
	</square>
	<square>
		<pieceId>3</pieceId>
		<line>1</line>
		<col>3</col>
		<black/>
	</square>
	<square>
		<pieceId>3</pieceId>
		<line>1</line>
		<col>6</col>
		<black/>
	</square>
	<square>
		<pieceId>4</pieceId>
		<line>1</line>
		<col>1</col>
		<black/>
	</square>
	<square>
		<pieceId>4</pieceId>
		<line>1</line>
		<col>8</col>
		<black/>
	</square>
	<square>
		<pieceId>5</pieceId>
		<line>1</line>
		<col>5</col>
		<black/>
	</square>
	<square>
		<pieceId>6</pieceId>
		<line>1</line>
		<col>4</col>
		<black/>
	</square>
	<square>
		<pieceId>0</pieceId>
		<line>6</line>
		<col>5</col>
		<none/>
	</square>
	<square>
		<pieceId>0</pieceId>
		<line>5</line>
		<col>5</col>
		<none/>
	</square>
</board_result>
