=== sergiowww/chessmine/trunk/chessmine/src/main/resources/board-state.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.wicstech.net/chessmine/board-state" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.wicstech.net/chessmine/board-state">

    <xsd:element name="board-state" type="Board-State"></xsd:element>
    
    <xsd:complexType name="Board-State">
    	<xsd:sequence>
    		<xsd:element name="piece" type="Piece" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    		<xsd:element name="boardSidePlaying" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Piece">
    	<xsd:sequence>
    		<xsd:element name="type" type="xsd:int" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="x" type="xsd:int" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="y" type="xsd:int" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="color" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== sergiowww/chessmine/trunk/chessmine/src/test/resources/check-mate2.xml
<?xml version="1.0" encoding="UTF-8"?>
<board-state xmlns="http://www.wicstech.net/chessmine/board-state" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wicstech.net/chessmine/board-state ../../main/resources/board-state.xsd ">
    <piece>
        <type>5</type>
        <x>3</x>
        <y>0</y>
        <color>BLACK</color>
    </piece>
    <piece>
        <type>5</type>
        <x>3</x>
        <y>2</y>
        <color>WHITE</color>
    </piece>
    <piece>
        <type>4</type>
        <x>6</x>
        <y>5</y>
        <color>WHITE</color>
    </piece>
    <boardSidePlaying>WHITE</boardSidePlaying>
</board-state>
